all: insertsort mergesort insertTime mergeTime

insertsort: insertsort.c
	gcc -g -std=gnu99 -Wall insertsort.c -o insertsort

mergesort: mergesort.c
	gcc -g -std=gnu99 -Wall mergesort.c -o mergesort

insertTime: insertTime.c
	gcc -g -std=gnu99 -Wall insertTime.c -o insertTime

mergeTime: mergeTime.c
	gcc -g -std=gnu99 -Wall mergeTime.c -o mergeTime

clean:
	rm insertsort mergesort insertTime mergeTime
